version: '3'

services:
  service-checker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      TELEGRAM_TOKEN: TELEGRAM_TOKEN
      CHAT_ID: CHAT_ID
    volumes:
      - ./vps_servers.json:/root/vps_servers.json
